### ISSUE TITLE
No access to the internal database

### ISSUE THREAD

**Issue by goekhanKahriman** [International-Data-Spaces-Association/IDS-ConfigurationManager#100]
After starting the configmanager and calling the url: http://localhost:8081/console and entering the credentials, which are set in the application.properties, nothing is shown in the web browser.

Following message appears: "localhost has refused the connection"

**Comment by tmberthold** [comment]
`http.headers().frameOptions().sameOrigin();`  needs to be added to the `SecurityConfig` (in de.fraunhofer.isst.configmanager.config package) to allow the H2-Colsole **iframes** to be displayed, otherwise SpringBoot disallows them for security reasons as default.
With the code above content of the CM-Backend is allowed to be displayed in iframes in general at least on pages under the same host/origin.
Must be tested to see if that would have unintended consequences. Is of course also a limitation of existing security policies.

![image](https://user-images.githubusercontent.com/75306992/113742151-9aeec480-9702-11eb-877d-66d858929c35.png)

**Comment by goekhanKahriman** [comment]
Thank you for your feedback. I will test it. I think it is necessary that the user of the confimanager have access to database to see which data is persisted.
