### ISSUE TITLE
[Shared DM] DSC v5 Integration

### ISSUE THREAD

**Issue by ob-silva** [International-Data-Spaces-Association/IDS-ConfigurationManager#134]
The configmanager should support the new DSC Version 5, which is now in pre-release.

**Comment by tmberthold** [comment]
Is put on hold for the time being

**Comment by freboy** [comment]
Hi!
I am interested in ConfigurationManager support for Dataspace Connector v5.0.x.
Do you have that uplift on the roadmap or could you please explain what you mean with "on hold"?

Best Regards,
F.B.

**Comment by tmberthold** [comment]
Thank you for asking!

In fact, we are working at full speed right now to connect the CM to the latest DSC version.

Compatibility with the latest version should therefore be available in the foreseeable future. Since this is an ongoing project, I would not want to communicate a specific date yet.

**Comment by tmberthold** [comment]
Currently, the goal is to have a common data store instead of communicating data via the APIs, see Issue https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/147 and the current status of the work that is taking place directly for this in the DSC: https://github.com/International-Data-Spaces-Association/DataspaceConnector/pull/262

**Comment by tmberthold** [comment]
New Branch for CM-Backend adjustments (WIP):
https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/commits/Dataspace-Connector-v5

**Comment by tmberthold** [comment]
***

<h3 align="center">
  <a href="https://github.com/International-Data-Spaces-Association/DataspaceConnector">
    -- End-Of-Support: 21.07.2021 -- Configmanager has been integrated directly into the Dataspace Connector.
  </a>
</h3>

***
