### ISSUE TITLE
Existing backend connections (generic endpoints) are not loaded from connector

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#45]
Existing backend connections (generic endpoints) from connector should be loaded at startup.

@tmberthold @goekhanKahriman

**Comment by tmberthold** [comment]
Problem: There is no list of endpoints from the connector which we could simply ask for. For the connector, a representation includes an endpoint, but there is no centralized management of edpoints so that an ID or similar could simply be referenced within the representation. In the GUI we accommodate the user and allow him to create a backend connection and reuse it. This data is in turn stored and managed by us in the CM backend. 

If they are now to be loaded at startup, I would first have to load the representations for all resources of the connector via an API call to the connector for each resource-representation (/admin/api/resources/{resource-id}/{representation-id}) and then load the backend connection data out of there. Then I would have to iterate over all the data and find out if there are duplicates (multiple resources in the same backend) and throw those duplicates out. 

The runtime of this when starting up CM increases noticeably with the number of resources and representations within the connector.

I would wait until there is a reasonable solution here.

**Comment by BastianWel** [comment]
You are right. The list of backend connections is just an additional functionality provided by the config manager to store URL and login data. So in my opinion it would be OK that after deleting the Configmanager DB this data is lost.
I close this issue.
