### ISSUE TITLE
POST ​/api​/ui​/generic​/endpoint not working with "%" character

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#80]
When calling `POST ​/api​/ui​/generic​/endpoint` with swagger and set `accessURL=http://backend?param=%` the request returns ERROR 500.
No error in Configmanager log.

**Comment by tmberthold** [comment]
Thanks for the feedback, will take a look.

**Comment by tmberthold** [comment]
Problem is identified: the used URI.create does not like **%** character, otherwise the method tries to de-escape the % and the following characters. But since it is an intentional %, this cannot work.

We have to look for an alternative solution.

**Comment by ob-silva** [comment]
This was happening because URI.create expects a RFC encoded string, spring boot however automatically decodes parameters when they're from type `String.` 

The fix was to change all accessURL parameters to type URI in all REST APIs.

This implies that URI `http://backend?param=%` would actually be saved as `http://backend?param=%25`,
which is the proper encoding. 

I've created a pull request to fix this issue.
https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/pull/108
