### ISSUE TITLE
ERROR 500 on POST ​/api​/ui​/approute

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/IDS-ConfigurationManager#81]
Most of the time creating routes works, but one time I got Error 500.
Configmanager log:
```
16:06:01.654 [http-nio-8081-exec-10] INFO - >> POST /approute description: addroutesconsumption_2021-03-25 - Unnamed
16:06:05.285 [http-nio-8081-exec-5] WARN - Resolved [org.springframework.web.bind.MissingServletRequestParameterException: Required URI parameter 'routeId' is not present]
16:06:05.310 [http-nio-8081-exec-1] WARN - Resolved [org.springframework.web.bind.MissingServletRequestParameterException: Required URI parameter 'routeId' is not present]
```

**Comment by tmberthold** [comment]
Thanks for the feedback, will take a look.

**Comment by tmberthold** [comment]
Just can't recreate with the new version 6, if I follow the process of adding routes in the GUI and do not take shortcuts.

The snippet of logs also indicates that the warnings do not belong to the POST of the /approute, since no routeId is required in the post-case, just the description. The numbers at exec-10, exec-5 and exec-1 also indicate that there were three different calls involved here.

The only possibility where this would be a case is if the user adds a new route, takes a shortcut in the GUI and already navigates back to the overview of routes and looks up the route-details of the new route, before the saving process of the new route has finished (didn't wait for green circle to go away). Then the case would be conceivable that still no routeId is present with the GET on the approute-details.
