### ISSUE TITLE
[Broker] Update edited resources at the broker

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/IDS-ConfigurationManager#83]
When editing resources, they are not updated at the broker

**Comment by vdakker** [comment]
I'm not sure if we shoud update resources at the Broker in the `ResourceUIController`, because it will add another call Configmanager<->DSC<->Broker into the `updateResource` message (which could cause timeouts or significant slowdown).

Maybe the Configmanager should maintain a Queue of what was Updated/Changed/Added and is not yet commited to the Brokers. Then the Configmanager could handle the Queue independently from the API calls.

**Comment by tmberthold** [comment]
In principle, I believe that it should be state of the art to be able to reflect changes made directly live at the Broker, if required.

We will look in more detail at the runtime required for API calls to return a response and how these can be improved.
